POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Hazim",
    "password" : "Aku"
}
###########
POST http://localhost:3000/reg


##########
GET http://localhost:3000/hai

##########
GET http://localhost:3000/hello

##########
