POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "aliff08",
  "password": "0987654321"
}

############################ NEW USER LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "Azzz",
  "password": "nzzzz"
}
################################ ADMIN LOGIN

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

######################### SECURITY
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "security",
  "password": "123456789"
}
############################### REGISTER USER BY ADMIN
POST http://localhost:5000/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4ifSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDQxNDczLCJleHAiOjE2ODgwNDMyNzN9.dCHZ9wpyutiLyFb3OOXrxO8ZI90zdPbWf3syhJG5Jhs

{
  "username": "Azzz",
  "password": "nzzzz",
  "name": "Albino Rafael",
  "email": "newuser@example.com",
  "role": "user"
}

############################### ADD VISITOR BY USER
POST http://localhost:5000/addvisitors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFsaWZmMDgiLCJwYXNzd29yZCI6IjA5ODc2NTQzMjEiLCJuYW1lIjoiYWxpZmZhaXphdCIsImVtYWlsIjoiYWxpZmpyNzYzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIn0sInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDQxNDI1LCJleHAiOjE2ODgwNDMyMjV9.TUpF6n0_ciolUHaY7Q5MKpIe3bqabpoXjjzG1hY7dl8

{
  "visitorname": "ayam",
  "id": "740612020453",
  "visitorpass": "ay1234",
  "phoneNumber": "0112456356",
  "email": "Ruben@gmail.com",
  "appointmentDate": "2023-06-23",
  "carPlate": "KER8195",
  "purpose": "Football Training",
  "destination": "Tasik UTeM",
  "registeredBy": "aliffaizat"
}

##################### VISITOR CHECKIN BY SECURITY
POST http://localhost:5000/checkin  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6InNlY3VyaXR5IiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJuYW1lIjoiUGFrIEd1YXJkIiwiZW1haWwiOiJQYWsgZ3VhcmQuY29tIiwicm9sZSI6InNlY3VyaXR5IiwiX2lkIjoiNjQ5ZDdhY2JiZmU3MTk2Y2RkZjI0YzAzIn0sInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTY4ODA0MzU5OSwiZXhwIjoxNjg4MDQ1Mzk5fQ.AEHxB_uSWEIKez0sUGcrv9iOmu6v3jmJIWzGlePzEOo

{
  "visitorpass": "ayam1234",
  "carplate": "KER8195"
}

############################# VISITOR CHECKOUT BY SECURITY
POST http://localhost:5000/checkout 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6InNlY3VyaXR5IiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJuYW1lIjoiUGFrIEd1YXJkIiwiZW1haWwiOiJQYWsgZ3VhcmQuY29tIiwicm9sZSI6InNlY3VyaXR5IiwiX2lkIjoiNjQ5ZDdhY2JiZmU3MTk2Y2RkZjI0YzAzIn0sInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTY4ODA0MzU5OSwiZXhwIjoxNjg4MDQ1Mzk5fQ.AEHxB_uSWEIKez0sUGcrv9iOmu6v3jmJIWzGlePzEOo

{
  "visitorpass": "ayam1234",
  "carplate":"KER8195"
}
############################# EDIT DATA BY USER
PATCH http://localhost:5000/editvisitor/64994ee23c9d03924720c246
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFsaWZmMDgiLCJwYXNzd29yZCI6IjA5ODc2NTQzMjEiLCJuYW1lIjoiYWxpZmZhaXphdCIsImVtYWlsIjoiYWxpZmpyNzYzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjQ5ZDdhY2JiZmU3MTk2Y2RkZjI0YzAyIn0sInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDQ0NjcwLCJleHAiOjE2ODgwNDY0NzB9.zuv1e3fiiA7Dh2eLRyE33CGNxyirlJEfrh45MtcORzQ

{
  "visitorname": "Ahmad Ahmad",
  "phoneNumber": "8555555555555555555",
  "appointmentDate": "2025-10-22"
}

###################################### DELETE DATA BY USER
DELETE http://localhost:5000/deletevisitor/64994ee23c9d03924720c246
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFsaWZmMDgiLCJwYXNzd29yZCI6IjA5ODc2NTQzMjEiLCJuYW1lIjoiYWxpZmZhaXphdCIsImVtYWlsIjoiYWxpZmpyNzYzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjQ5ZDdhY2JiZmU3MTk2Y2RkZjI0YzAyIn0sInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDQ0NjcwLCJleHAiOjE2ODgwNDY0NzB9.zuv1e3fiiA7Dh2eLRyE33CGNxyirlJEfrh45MtcORzQ


####################################### ALL VISITOR ADMIN SECURITY
GET http://localhost:5000/visitorinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4ifSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDQ1NzY4LCJleHAiOjE2ODgwNDc1Njh9.1phXdB_pjoggUAEw2p-g9vJwoJZ2itL9qZly9N-OMoE

############################################ USER BY VISITOR NAME
GET http://localhost:5000/visitorinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImFsaWZmMDgiLCJwYXNzd29yZCI6IjA5ODc2NTQzMjEiLCJuYW1lIjoiYWxpZmZhaXphdCIsImVtYWlsIjoiYWxpZmpyNzYzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjQ5OTRkZTUzYzlkMDM5MjQ3MjBjMjQyIn0sInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzY4NzQzLCJleHAiOjE2ODc3NzA1NDN9.NKRdD7nA9u6-KXb4vfLZSunOPv0LYFGl7-Yy4K0ai08

{
 "registeredBy": "aliffaizat"
}

